### ISSUE TITLE
UserWarning: torch.utils._pytree._register_pytree_node is deprecated.

### ISSUE THREAD

**Issue by Roboxkin** [gnana70/tamil_ocr#59]
When running in the console UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
   _torch_pytree._register_pytree_node(

How can this be fixed?
Thank you!

**Comment by gnana70** [comment]
Hi @Roboxkin , kindly share me pytorch, torchvision, python versions along with OS details.

**Comment by gnana70** [comment]
Closing this issue due to no response. Feel free to reopen the issue if it's still persists.
