### ISSUE TITLE
Training and Testing Data

### ISSUE THREAD

**Issue by Abhiram4572** [gnana70/tamil_ocr#62]
Hi, 

Firstly, a great work. I am interested to know about the training data and testing data used? Could you please share details regarding the same? Any plans to release them?

Thanks,

**Comment by gnana70** [comment]
Hi @Abhiram4572 , Model has trained on 7 million data and validated against 0.5 million data.

**Comment by Abhiram4572** [comment]
Thanks for the response. How did you get this dataset? Is this a public dataset?  Is it synthetically generated dataset? Can you please share more light on this?

thanks,

**Comment by gnana70** [comment]
It's synthetic dataset
